
on:
  workflow_dispatch:
  
jobs:
  build-docker-image:
    name: Build Docker Image
    uses: kylecannon-8451/wf_calls/.github/workflows/dockerbuild.yml@main
    with:
      image-name: "my-app"

 
  
    

      
 
